# Generated by Django 4.2.2 on 2023-06-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_surname', models.CharField(max_length=20)),
                ('user_nick', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_date', models.DateField()),
                ('user_visit', models.CharField(max_length=40)),
                ('why_we', models.TextField()),
                ('why_filial', models.TextField()),
                ('computer_work', models.TextField()),
                ('administration_work', models.CharField(max_length=4)),
            ],
        ),
    ]
