# Generated by Django 4.2.2 on 2023-06-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_alter_quiz_administration_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='a',
            field=models.IntegerField(null=True),
        ),
    ]
