# Generated by Django 4.2.2 on 2023-06-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_quiz_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='a',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='administration_work',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
